version: 1.0.{build}-{branch}

branches:
  only:
  - master
  - develop

image: Visual Studio 2015

platform: Any CPU

build:
  parallel: true

install:
 - ps: .\Galt\Bootstrap.ps1

build_script:
 - dotnet run -p Galt\src\CodeCakeBuilder -nointeraction
 - nunit-console Galt\src\ClassLibrary1\bin\Release\netstandard1.6\ClassLibrary1.dll
